version: '3'
services:
  db:
    ports:
      - "5432:5432"
    container_name: db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=TT
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./data:/var/lib/mysql
    restart: always
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/TT
      DB_USER: postgres
      DB_PASSWORD: admin
    depends_on:
      - db
    restart: always
