version: '3'
services:
  db:
    ports:
      - "5432:5432"
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./data:/var/lib/mysql
    restart: always
  backend:
    image: ${IMAGE}
    container_name: backend
    ports:
      - "80:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      URL_PATH: ${URL_PATH}
    volumes:
      - ./statics/images:/media
    depends_on:
      - db
    restart: always
